language: node_js
node_js:
  - "stable"
services:
  - docker
before_install:
  - docker build -t sebastiansym/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true sebastiansym/docker-react npm run test -- --coverage